### PR TITLE
Increase score from infection/infection

### PR DESCRIPTION
**Pull request by fredden**
This pull request
- Increases the time-out for mutation tests, allowing more tests to run to completion
- Require 100% mutation coverage
- Marks certain code paths as not relevant for mutation testing
- Replaces regular expression with simple string comparison in `src/Format/NewLine.php`
- Increases test coverage
- Increases mutation coverage score
- Resolves two psalm complaints

### CODE REVIEW

**Comment by localheinz** [comment]
Let me think about this, @fredden - I almost fell asleep running mutation tests here!

**Comment by fredden** [comment]
> Let me think about this

No problem; it's your repository/code after all. :)

> I almost fell asleep running mutation tests here!

On my set-up, the mutation tests take around 1.5 minutes on the `main` branch and around 3.5 minutes here. If I put the time-out back to 10 seconds in `infection.json`, then then tests take around 1 minute, but half of the tests are skipped again (like they already are on the `main` branch).

Would you be interested in a pull request which just improves test coverage and doesn't add any "ignore infection test" comments and leaves the `infection.json` as-is?

**Comment by localheinz** [comment]
@fredden 

> Would you be interested in a pull request which just improves test coverage and doesn't add any "ignore infection test" comments and leaves the infection.json as-is?

Yes, that would be great!

**Comment by localheinz** [comment]
@fredden 

Can we close this in favour of #993?

**Comment by fredden** [comment]
I've rebased this following the merge of #993. It looks like there are a couple of mutants escaping still here. I'll try to find some time to sort these out.

@localheinz you're welcome to close this. I don't particularly like all the "ignore" comments that were needed to get to 100% from this tool, and I recall that you seemed against increasing the timeout to get better coverage/reporting.

**Comment by localheinz** [comment]
Thank you for your work on this, @fredden - but I have decided to close this!

**Pull request closed without merging**
