### PR TITLE
Revert ‘Remove leading 'v' character from version strings’

### LINKED ISSUE #1045: The version number prefix is not consistent with the composer specification
Currently,  the package will be delete the 'v' prefix of version number but in the [composer doc](https://getcomposer.org/doc/04-schema.md#version) or [schema](https://getcomposer.org/schema.json) the 'v' prefix is allowed, so I want them to keep be consistent, I would like to hear your thoughts on this.

### PR DESCRIPTION
**Pull request by kayw-geek**
Composer has now fixed this [bug](https://github.com/composer/composer/pull/11764), so does this imply that Composer considers this manner of writing version numbers as acceptable? Furthermore, since the current [composer doc](https://getcomposer.org/doc/04-schema.md#version) and [schema](https://getcomposer.org/schema.json) do not mandate that version numbers must exclude the 'v' prefix, should we consider removing the behavior that strips away the 'v' prefix?

Fixes #1045

### CODE REVIEW

**Comment by fredden** [comment]
@kayw-geek #1003 and https://github.com/composer/composer/issues/11723 are different bugs.
This pull request currently reintroduces the bug described in #1003 (by exactly reverting the whole fix thereof, including its tests).

I think what you want to do is create a new rule to ensure that raw version numbers are always prefixed by the optional `v` character (or maybe `V`, but consistency is important). I prefer to omit this, which is the current behaviour of this library.

**Comment by kayw-geek** [comment]
@fredden I don't think the following example v should be deleted 
```diff
+ "xxx: 1.0.0"
- "xxx: v1.0.0"
```

**Comment by fredden** [comment]
@kayw-geek please reinstate the tests here for #1003.

You will probably need to change several test outputs when you write the code to always prefix version numbers with "v" (adding where absent, and replacing "V" if found). The changes you propose should not reintroduce already-fixed bugs. Removing tests typically isn't the ideal way of making the test-suite pass.

Please include a test where normalising `^1.2 || ~3.4.5 || 6.7.8 || ^9.0` results in a sensible sorting order.

**Comment by kayw-geek** [comment]
Hi @fredden, I have modified the code as you suggested, Can you help review if you have time?

**Comment by fredden** [comment]
Thanks for the update.

1. I don't see any code to add the missing "v" character when absent.
2. I don't see any code to replace the "V" character with "v" when found.
3. Please add tests\* to ensure that (at least) the following constraints are normalised as expected: `1`, `1.2`, `1.2.3`, `V2.3.4`, `^V4.5`, `~V7.8.9`.
4. Please revert / don't make any changes in `test/Fixture/Vendor/Composer/...`; I would expect to see your changes somewhere in `test/Template/Vendor/Composer/...`.

\* Some of these are covered by existing test cases, but adding a new set of tests that specifically covers this feature makes most sense to me. Perhaps we need to move all the tests in `test/Template/Vendor/Composer/ComposerJsonNormalizer/NormalizeNormalizesJson/Json/IsObject/HasEntries/Yes/HasProperty/ValueContainsPackagesAndVersionConstraints/HasEntries/Yes/HasNormalizedVersionConstraints/No/LeadingV/` into a new `LowerCase` directory, and create new tests for `UpperCase`, `Absent`, `Mixed`, etc.

**Comment by fredden** [comment]
It's probably worth noting that I don't agree with this feature / change. I'll help get it into a potentially-accepted state, but it's completely up to @localheinz if this will be accepted or not.

**Pull request closed without merging**
